language: swift
osx_image: xcode10

cache: bundler

notifications:
  email: false

before_install:
  - gem install bundler # keep bundler up-to-date

before_script:
  #- pod update JacKit MudoxKit GitHubKit SocialKit # switch to use `:git =>` sources
  - pod update JacKit MudoxKit GitHubKit # switch to use `:git =>` sources

script:
  - bundle exec fastlane ios test

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Hydra'
