# vim: ft=ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Build and test with code coverage"
  lane :test do

    workspace = "Hydra.xcworkspace"
    project = "Hydra.xcodeproj"
    scheme = "Hydra"
    targetDevices = ["iPhone 8"]

    run_tests(
      workspace: workspace,
      scheme: scheme,
      devices: targetDevices,
      code_coverage: true,
    )

  end

end
